//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoccerDiv.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Admin
    {
        public int Admin_ID { get; set; }

        [Required(ErrorMessage = "Enter Admin Name!!")]
        [Display(Name = "Admin Name")]
        public string Admin_Name { get; set; }

        [Required(ErrorMessage = "Enter admin Email")]
        [EmailAddress]
        [Display(Name = "Email")]
        [DataType(DataType.EmailAddress)]
        public string Admin_Email { get; set; }

        [Required(ErrorMessage = "Enter admin Password")]
        [Display(Name = "Password")]
        [DataType(DataType.Password)]
        [MaxLength(20, ErrorMessage = "Maximum 20 characters allowed")]
        [MinLength(6, ErrorMessage = "Atleast 6 character required")]
        public string Admin_Password { get; set; }

        [Display(Name = "Admin Image")]
        public string Admin_Image { get; set; }

        [Display(Name = "Description")]
        public string Admin_Dexcription { get; set; }

        public HttpPostedFileBase AdminImageFile { get; set; }
    }
}
