//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoccerDiv.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Coach
    {

        public int Coach_ID { get; set; }

        [Required(ErrorMessage = "Choose sports!!")]
        [Display(Name = "Sports Name")]
        public int Sports_ID { get; set; }

        [Required(ErrorMessage = "Choose your favourite team!!")]
        [Display(Name = "Team Name")]
        public int Team_ID { get; set; }

        [Required(ErrorMessage = "Enter coach name!!")]
        [Display(Name = "Name")]
        public string Coach_Name { get; set; }

        [Required(ErrorMessage = "Enter coach age!!")]
        [Display(Name = "Team Name")]
        public Nullable<int> Coach_Age { get; set; }

        [Required(ErrorMessage = "Enter nationality!!")]
        [Display(Name = "Nationality")]
        public string Coach_Nationality { get; set; }

        [Display(Name = "Coach Image")]
        public string Coach_Image { get; set; }

        public HttpPostedFileBase CoachImageFile { get; set; }

        public virtual Sport Sport { get; set; }
        public virtual Team Team { get; set; }
    }
}
