//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoccerDiv.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Contact
    {
        public int Contact_ID { get; set; }

        [Required(ErrorMessage = "Enter your name!!")]
        [Display(Name = "C Name")]
        public string C_Name { get; set; }

        [Required(ErrorMessage = "Enter your Email")]
        [EmailAddress]
        [Display(Name = "C Email")]
        public string C_Email { get; set; }

        [Required(ErrorMessage = "Enter your message")]
        [Display(Name = "Message")]
        public string C_Message { get; set; }
    }
}
