//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoccerDiv.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Player
    {

        public int Player_ID { get; set; }

        [Required(ErrorMessage = "Choose sports!!")]
        [Display(Name = "Sports Name")]
        public int Sports_ID { get; set; }

        [Required(ErrorMessage = "Choose player team!!")]
        [Display(Name = "Team Name")]
        public int Team_ID { get; set; }

        [Required(ErrorMessage = "Enter player name!!")]
        [Display(Name = "Player Name")]
        public string Player_Name { get; set; }

        [Required(ErrorMessage = "Enter Player age!!")]
        [Display(Name = "Age")]
        [Range(10, 50)]
        public int Player_Age { get; set; }

        [Required(ErrorMessage = "Enter Player Nationality!!")]
        [Display(Name = "Nationality")]
        public string Player_Nationality { get; set; }

        [Required(ErrorMessage = "Enter Player position!!")]
        [Display(Name = "Position")]
        public string Player_Position { get; set; }

        [Display(Name = "Player Rating")]
        public Nullable<double> Player_Rating { get; set; }

        [Display(Name = "Player Ranking")]
        public Nullable<short> Player_Ranking { get; set; }

        [Display(Name = "Player Image")]
        public string Player_Image { get; set; }

        public HttpPostedFileBase PlayerImageFile { get; set; }

        public virtual Sport Sport { get; set; }
        public virtual Team Team { get; set; }
    }
}
