//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoccerDiv.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Team
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Team()
        {
            this.Coaches = new HashSet<Coach>();
            this.Customers = new HashSet<Customer>();
            this.Events = new HashSet<Event>();
            this.Events1 = new HashSet<Event>();
            this.Players = new HashSet<Player>();
        }

        public int Team_ID { get; set; }

        [Required(ErrorMessage = "Enter the sports name!!")]
        [Display(Name = "Sports Name")]
        public int Sports_ID { get; set; }

        [Required(ErrorMessage = "Enter the Team name!!")]
        [Display(Name = "Team Name")]
        public string Team_Name { get; set; }

        [Required(ErrorMessage = "Write a short description")]
        [Display(Name = "Team Description")]
        public string Team_Description { get; set; }

        [Display(Name = "Team Rating")]
        public Nullable<double> Team_Rating { get; set; }

        [Display(Name = "Team Ranking")]
        public Nullable<short> Team_Ranking { get; set; }

        [Display(Name = "Team Logo")]
        public string Team_Logo { get; set; }

        [Required(ErrorMessage = "Team country")]
        [Display(Name = "Team Country")]
        public string Team_Country { get; set; }

        public HttpPostedFileBase TeamImageFile{ get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Coach> Coaches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> Customers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Event> Events { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Event> Events1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Player> Players { get; set; }
        public virtual Sport Sport { get; set; }
    }
}
