//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoccerDiv.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Tournamnet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tournamnet()
        {
            this.Events = new HashSet<Event>();
        }

        public int Tournament_ID { get; set; }

        [Required(ErrorMessage = "Enter Sports Name!!")]
        [Display(Name = "Sports Name")]
        public int Sports_ID { get; set; }

        [Required(ErrorMessage = "Enter tournaments name!!")]
        [Display(Name = "Tournaments Name")]
        public string Tournament_Name { get; set; }

        [Required(ErrorMessage = "Enter tournament description!!")]
        [Display(Name = "Tournament Description")]
        public string Tournament_Description { get; set; }

        [Display(Name = "Tournament Logo")]
        public string Tournament_Logo { get; set; }

        public HttpPostedFileBase TournamentImageFile { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Event> Events { get; set; }
        public virtual Sport Sport { get; set; }
    }
}
