//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoccerDiv.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Venue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Venue()
        {
            this.Events = new HashSet<Event>();
        }

        public int Venue_ID { get; set; }

        [Required(ErrorMessage = "Enter Venue Name!!")]
        [Display(Name = "Venue Name")]
        public string Venue_Name { get; set; }

        [Required(ErrorMessage = "Enter capacity!!")]
        [Display(Name = "Capacity")]
        public Nullable<int> Venue_Capacity { get; set; }

        [Required(ErrorMessage = "Enter venue location!!")]
        [Display(Name = "Location")]
        public string Venue_Location { get; set; }

        [Display(Name = "Venue Image")]
        public string Venue_Image { get; set; }

        public HttpPostedFileBase VenueImageFile { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Event> Events { get; set; }
    }
}
